routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to( url('login') );
});

Route::get('/logout', function(){
    \Auth::logout();
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth'] ], function(){
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('caja', 'CajaController');
    Route::get('reportes/caja', 'CajaController@resumen')->name('resumen_de_caja');
    Route::get('reportes/tipo', 'CajaController@tipoDeReporte')->name('tipos_reportes_caja');
    Route::get('caja/reportes/dia/{dia_id}', 'CajaController@reporteDia');
    Route::resource('/comidas', 'ComidaController', [
        'names' => [
            'index' => 'comidas'
        ]
    ]);
    Route::resource('categorias', 'CategoriaController', [
        'names' => [
            'index' => 'categorias'
        ]
    ]);
    Route::resource('/combos', 'ComboComidaController', [
        'names' => [
            'index' => 'combos'
        ]
    ]);
    Route::resource('facturacion', 'FacturaController', [
        'names' => [
            'index' => 'pedidos',
            'create' => 'pedidos.create',
            'edit' => 'pedidos.edit',
            'update' => 'pedidos.update',
            'destroy' => 'pedidos.destroy'
        ]
    ]);
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/dashboard/pedidos/create.blade.php
@extends('layouts.dashboard_app_control')
@extends('layouts.dashboard_app_control')
@section('title', 'Carta')
@extends('layouts.dashboard_app_control')
@section('title', 'Nuevo pedido')
@section('title_for_wrapper', 'Pedidos')
@section('panel_header', 'Nuevo pedido')

<div class="container">
    @section('dash_content')
        <form action="">
            <div class="row">
                <div class="col-sm-5 col-lg-5 col-md-5">
                    <label for="">Codigo</label>
                    <input type="text" onkeyup="buscarProducto(event, this)" name="codigo" id="codigo" class="form-control">
                </div>
            </div>
        </form>
    @endsection
</div>
@section('jquery')

<script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('bower_components/select2/dist/js/select2.full.min.js') }}"></script>
<script>
  $(document).ready( function(){
    $('.table1').DataTable();
  });

  function deleteRow(e, btn){
    if( confirm('¿Seguro de que desea realizar esta accion?') ){
        url = btn.getAttribute('url');
        $.post(url, {"_method": "DELETE", "_token": "{{ csrf_token() }}"}, function(response){
            alert(response.message);
            location.reload();
        });
      }
  }

  function buscarProducto(e, input){
      let url = location.protocol+'//'+location.host+'/dashboard/comidas/'+input.value;
      if( input.value.length >= 6 ){
          $.getJSON(url, {}, function(response){
              if(!response.error){
                  let row = `
                    <tr>
                        <input type="hidden" name="producto_id[]" value="${response.registro.id}" />
                        <td>${response.registro.codigo}</td>
                        <td>${response.registro.nombre}</td>
                        <td>${response.registro.costo}</td>
                    </tr>
                  `
              }
          });
      }
  }

</script>

@endsection

resources/views/dashboard/pedidos/index.blade.php
@extends('layouts.dashboard_app_control')
@extends('layouts.dashboard_app_control')
@section('title', 'Carta')
@extends('layouts.dashboard_app_control')
@section('title', 'Gestion de categorias')
@section('title_for_wrapper', 'Categorias')
@section('panel_header', 'Categorias disponibles')

<div class="container">
    @section('dash_content')
        <div class="row">
            <div class="col-sm-4 col-lg-4 col-md-4">
                <a href="{{ route('categorias.create') }}" class="btn btn-app">
                    <i class="fa fa-plus"></i>
                    Agregar una
                </a>
            </div>
        </div>
        <div class="row"> 
            <div class="col-sm-12 col-lg-12 col-md-12">
                <table class="table table-stripped table1">
                    <thead>
                        <tr>
                            <th>ID #</th>
                            <th>Fecha</th>
                            <th>Total</th>
                            <th>Usuario</th>
                            <th>Estado</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pedidos as $pedido)
                            <tr style="text-align: center;">
                                <td>{{$pedido->id}}</td>
                                <td>{{$pedido->emision->format('Y-m-d H:i')}}</td>
                                <td>{{$pedido->total}}</td>
                                <td>{{$pedido->titular->name.' '.$pedido->lastname}}</td>
                                <td>
                                    <div class="label label-success">
                                        {{$pedido->estado_pedido}}
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ route('pedidos')."/$pedido->id" }}" class="btn btn-success">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endsection
</div>
@section('jquery')

<script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('bower_components/select2/dist/js/select2.full.min.js') }}"></script>
<script>
  $(document).ready( function(){
    $('.table1').DataTable();
  });

  function deleteRow(e, btn){
    if( confirm('¿Seguro de que desea realizar esta accion?') ){
        url = btn.getAttribute('url');
        $.post(url, {"_method": "DELETE", "_token": "{{ csrf_token() }}"}, function(response){
            alert(response.message);
            location.reload();
        });
      }
  }

</script>

@endsection

resources/views/dashboard/pedidos/show.blade.php
@extends('layouts.dashboard_app_control')
@extends('layouts.dashboard_app_control')
@section('title', 'Carta')
@extends('layouts.dashboard_app_control')
@section('title', 'Detalles de pedido')
@section('title_for_wrapper', 'Pedido')
@section('panel_header', 'Detalles de pedido')

<div class="container">
    @section('dash_content')
        <form action="{{ route("pedidos.update", [$pedido->id]) }}" method="post">
            @csrf
            @method('PUT')
            <input type="hidden" name="user_registrador_id" value="{{$user->id}}" id="">
            <div class="row">
                <div class="col-sm-2 col-md-2 col-lg-2">
                    <a href="{{ route("pedidos") }}" class="btn btn-danger">
                        Volver atras
                    </a>
                </div>
                <div class="col-sm-2 col-lg-2 col-md-2 col-md-offset-4 col-lg-offset-8">
                    <button class="btn btn-success">
                        Procesar pedido
                    </button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2 col-md-2 col-lg-2">
                    <label for="">Usuario</label>
                    <input type="text" class="form-control" value="{{$pedido->titular->name.' '.$pedido->titular->lastname}}" disabled="disabled" readonly="readonly" id="user">   
                </div>
                <div class="col-sm-2 col-lg-2 col-md-2">
                    <label for="">Fecha y hora</label>
                    <input type="text" value="{{$pedido->emision->format('Y-m-d H:i')}}" class="form-control" disabled="disabled" readonly="readonly" id="fecha">
                </div>
                <div class="col-sm-2 col-lg-2 col-md-2">
                    <label for=""># de pedido</label>
                    <input type="text" value="{{$pedido->id}}" class="form-control" readonly="readonly" disabled="disabled" id="numero">
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2">
                    <label for="">Estado</label>
                    <input type="text" value="{{$pedido->estado_pedido}}" readonly="readonly" disabled="disabled" class="form-control">
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2">
                    <label for="">Subtotal</label>
                    <input type="text" value="{{$pedido->subtotal}}" readonly="readonly" disabled="disabled" class="form-control">
                </div>
                <div class="col-sm-2 col-lg-2 col-md-2">
                    <label for="">Total</label>
                    <input type="text" value="{{$pedido->total}}" readonly="readonly" class="form-control" disabled="disabled" class="form-contro">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-lg-12 col-md-12">
                    <h3 class="page-header">Detalles</h3>
                </div>
            </div>
            <div class="row-col-md-12 col-lg-12 col-sm-12">
                <table class="table table1 table-striped">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Descripción</th>
                            <th>Cantidad</th>
                            <th>Precio unitario</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach( $pedido->detalles as $detalle )
                            @php
                                $tipo = $detalle->comida_id != 1 ? $detalle->comida : $detalle->combos;
                            @endphp
                            <tr>
                                <td>{{$tipo->nombre}}</td>
                                <td>{{$tipo->descripcion}}</td>
                                <td>{{$detalle->cantidad}}</td>
                                <td>{{$tipo->costo}}</td>
                                <td>{{$detalle->cantidad * $tipo->costo}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </form>
    @endsection
</div>
@section('jquery')

<script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('bower_components/select2/dist/js/select2.full.min.js') }}"></script>
<script>
  $(document).ready( function(){
    $('.table1').DataTable();
  });

  function deleteRow(e, btn){
    if( confirm('¿Seguro de que desea realizar esta accion?') ){
        url = btn.getAttribute('url');
        $.post(url, {"_method": "DELETE", "_token": "{{ csrf_token() }}"}, function(response){
            alert(response.message);
            location.reload();
        });
      }
  }

</script>

@endsection